spring:
  profiles:    active: smart  mvc:    format:      date-time: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
hr:
  def: 5
  smartDefault: 0
  
  limits:
    - 2.5
    - 15
    - 5
    
  percents:
    - 2
    - 5
    - 10
    
server:
  port: 8081