spring:
  profiles:    active: smart  mvc:    format:
      date: yyyy-MM-dd      date-time: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:      ddl-auto: create
  datasource:    url: jdbc:postgresql://localhost:5432/hr
    username: postgres
    password: dinoking
hr:
  def: 5
  smartDefault: 0
  secret: "secret"
  issuer: "KD"
  expiryInMinutes: 12
  
  limits:
    - 2.5
    - 15
    - 5
    
  percents:
    - 2
    - 5
    - 10
    
server:
  port: 8081
  
  error:
    include-message: always
    
logging:
  level:    '[org.springframework.security]': debug