spring:
  profiles:    active: smart  mvc:    format:      date-time: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    hibernate:      ddl-auto: update
  datasource:    url: jdbc:postgresql://localhost:5432/hr
    username: postgres
    password: dinoking
hr:
  def: 5
  smartDefault: 0
  
  limits:
    - 2.5
    - 15
    - 5
    
  percents:
    - 2
    - 5
    - 10
    
server:
  port: 8081
  
  error:
    include-message: always